### ISSUE TITLE
Link error when running setup_cuda.py

### ISSUE THREAD

**Issue by nikkris** [MrGF/py-faster-rcnn-windows#12]
Hi, I am getting the following error when running the setup_cuda.py file

Command: 

python setup_cuda.py build_ext --inplace

Error log:

LINK : fatal error LNK1181: cannot open input file 'ID=2.obj'
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin\\nvcc.exe' failed with exit status 2

I am not able to find any "2.obj" in the project folder. 

More information:

I edited the sm architecture in setup_cuda.py from '--arch=sm_35' to '--arch=sm_60' as I have a Pascal GPU. Is there some obvious setting that I have missed?

**Comment by liangzz1991** [comment]
i met same problem!!　　？？？

**Comment by pkranen** [comment]
For me the following made it work: add this hack to setup_cuda.py in line 118:

```
        if any('-LC' in x for x in cmd):
            # if you get "fatal error C1083: Cannot open include file: 'stddef.h'" add the folder that contains this file on your machine like this:
            cmd.append(r"-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt")
            # if you get "fatal error LNK1181: cannot open input file 'ID=2.obj'" remove the ",ID=2" bit from the command:
            for i, x in enumerate(cmd):
                if ',ID=2' in x:
                    cmd[i] = x.replace(',ID=2', '')
        
        spawn(cmd, search_path, verbose, dry_run)
```

**Comment by nikkris** [comment]
Thanks a lot! Your hack worked.

**Comment by rmxhhh** [comment]
@pkranen  Hi,when i add the hack:
`if any('-LC' in x for x in cmd):
            # if you get "fatal error C1083: Cannot open include file: 'stddef.h'" add the folder that contains this file on your machine like this:
            cmd.append(r"-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt")
            # if you get "fatal error LNK1181: cannot open input file 'ID=2.obj'" remove the ",ID=2" bit from the command:
            for i, x in enumerate(cmd):
                if ',ID=2' in x:
                    cmd[i] = x.replace(',ID=2', '')
        spawn(cmd, search_path, verbose, dry_run)`
the erro occur:
` File "setup_cuda.py", line 118
    if any('-LC' in x for x in cmd):
                                   ^
IndentationError: unindent does not match any outer indentation level`
